name: user-statistician

on:
  schedule:
    - cron: '42 4 * * *'
  workflow_dispatch:

jobs:
  stats:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2

    - name: Generate the user stats image for personal website
      uses: cicirello/user-statistician@v1
      with:
        colors: '#f6f0bb #862d2d #862d2d #862d2d #305030'
        animated-language-chart: true
        featured-repository: Chips-n-Salsa
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
